[package]
name = "Hollow"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.10.0"
slint = { version = "1.15.1", features = ["backend-winit"]}
i-slint-backend-winit = "1.15.1"

[build-dependencies]
slint-build = "1.14.1"
